#!/bin/bash
# Author: Trevon Williams

url=$2
name="${3##*/}"
project="${2,,}"
option="${1,,}"

# For Storing previous cases
# making sure file is created
if [ ! -f history ]; then 
	touch history
fi

UI=$(cat history | grep UI | sed 's/UI: //')
API=$(cat history | grep API | sed 's/API: //')

currentUI=$(cat history | grep UI)
currentAPI=$(cat history | grep API)

case $option in
	"start") ./scripts/start $project $UI $API;;
	"setrepo") ./scripts/setrepo $project $name ;;
	"stop") ./scripts/stop $project ;;
    "update") ./scripts/update $project $name ;;
    *) echo -e "Sorry that is not an option, please refer to the man page\n'man deploy'"
esac

