#!/bin/bash
shell="$(echo $SHELL | sed 's/\/bin//')"

if [[ $shell =~ "zsh" ]]; then
	status=$(cat ~/.zshrc | grep MongoLaunchPad)
	if [[ -z $status ]]; then
		echo -e "\n# MongoLaunchPad Settings" >> ~/.zshrc
		pwd | xargs -I {} echo "PATH=$PATH:{}" >> ~/.zshrc
        s=$(find ~/ -name MongoLaunchPad) 
        echo "export MONGO=$s" >> ~/.zshrc && source ~/.zshrc
	fi
else
	status=$(cat ~/.bashrc | grep MongoLaunchPad)
	if [[ -z $status ]]; then
		echo -e "\n# MongoLaunchPad Settings" >> ~/.bashrc
		pwd | xargs -I {} echo "PATH=$PATH:{}" >> ~/.bashrc
        s=$(find ~/ -name MongoLaunchPad) 
        echo "export MONGO=$s" >> ~/.bashrc && source ~/.bashrc
	fi
fi
echo "Enjoy"
