#!/bin/bash

project=$2
url=$2

function getApi {
	clear
 	if [ -d app/$project/$name ]; then
 		echo "Are you sure you want to overrite this API? [Y/n]"
 		read y
 		if [ ! "${y,,}" == 'n' ]; then
 			rm -fr $MONGO/app/$project/$name && git clone $url $MONGO/app/$project/$name --quiet
 		fi
 		exit
 	else
 		git clone $url $MONGO/app/$project/$name --quiet
 	fi
	exit
}

case $project in 
	"api") getApi ;;
	"ui") gqetUI ;; 
	*) echo -e "\n Sorry, I do not know what you needs to be done.\n Correct options are as follows:"\
				"\n\t- deploy get api [url]\n\t- deploy get ui [url]\n"
esac