#!/bin/bash

function getApi {
	clear
 	if [ -d app/$project/$name ]; then
 		echo "Are you sure you want to overrite this API? ( y | n)"
 		read y
 		if [ "${y,,}" == 'y' ]; then
 			rm -fr $MONGO/app/$project/$name && git clone $url $MONGO/app/$project/$name --quiet
 		fi
 	else
 		git clone $url $MONGO/app/$project/$name --quiet
 	fi
	exit
}