#!/bin/bash

project=$1
name=$2
status=$(ls $project)

if [ -z $name ]; then
	echo "You did not set a repo for starting"
	exit
fi

# Setting API for use
function setApi {
	if [ ! -d $MONGO/$project/$name ]; then
		echo "No API project has been installed with that name"
		if [ -z status ]; then 
			echo "Make sure you have cloned a project"
		else
			echo -e "Current options include:"
			ls $project
			exit
		fi
	fi

	echo "API: $name" > $MONGO/source/history
	if [ -z $currentUI ]; then
		echo -e "Make sure you set the current UI"
	else 
		echo $currentUI >> $MONGO/source/history
	fi
	exit
}

function setUi {
	if [ ! -d $MONGO/$project/$name ]; then
		echo "No UI project has been installed with that name"
		if [ -z status ]; then 
			echo "Make sure you have cloned a project"
		else
			echo -e "Current options include:\n"
			cd ../$project && ls
			exit
		fi
	fi

	echo "UI: $name" > $MONGO/source/history
	if [ -z $currentAPI ]; then
		echo "Make sure you set the current API"
	else
	echo $currentAPI >> $MONGO/source/history	
	fi
	exit
}

case $project in 
	"api") setApi ;;
	"ui") setUi ;; 
	*) echo -e "\n Sorry, I don't know what you need to be done.\n Correct options are as follows:"\
				"\n\t- deploy set [api]\n\t- deploy set [ui]"
esac